export const DISPLAY_ALERT='SHOW_ALERT';
export const CLEAR_ALERT='CLEAR_ALERT';

export const GET_SINGLE_PRODUCT_BEGIN = 'GET_SINGLE_PRODUCT_BEGIN'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'
export const GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR'


export const REGISTER_USER_BEGIN='REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS='REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR='REGISTER_USER_ERROR';

export const LOGIN_USER_BEGIN='LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR='LOGIN_USER_ERROR';

export const HANDLE_CHANGE='HANDLE_CHANGE';

export const CREATE_CERERE_BEGIN='CREATE_CERERE_BEGIN';
export const CREATE_CERERE_SUCCESS='CREATE_CERERE_SUCCESS';
export const CREATE_CERERE_ERROR='CREATE_CERERE_ERROR';

export const EDIT_CERERE_BEGIN='EDIT_CERERE_BEGIN';
export const EDIT_CERERE_SUCCESS='EDIT_CERERE_SUCCESS';
export const EDIT_CERERE_ERROR='EDIT_CERERE_ERROR';

export const EDIT_CONTRACT_BEGIN='EDIT_CONTRACT_BEGIN';
export const EDIT_CONTRACT_SUCCESS='EDIT_CONTRACT_SUCCESS';
export const EDIT_CONTRACT_ERROR='EDIT_CONTRACT_ERROR';

export const CREATE_CONTRACT_BEGIN='CREATE_CONTRACT_BEGIN';
export const CREATE_CONTRACT_SUCCESS='CREATE_CONTRACT_SUCCESS';
export const CREATE_CONTRACT_ERROR='CREATE_CONTRACT_ERROR';

export const LOGOUT_USER='LOGOUT_USER';

export const SIDEBAR_OPEN = 'SIDEBAR_OPEN'
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE'

export const GET_CERERI_BEGIN='GET_CERERI_BEGIN'
export const GET_CERERI_SUCCESS='GET_CERERI_SUCCESS'

export const DELETE_CERERI_BEGIN='DELETE_CERERI_BEGIN'

export const GET_CONTRACT_BEGIN='GET_CONTRACT_BEGIN'
export const GET_CONTRACT_SUCCESS='GET_CONTRACT_SUCCESS'

export const DELETE_CONTRACT_BEGIN='DELETE_CONTRACT_BEGIN'


export const GET_SINGLE_CERERI_BEGIN='GET_SINGLE_CERERI_BEGIN'
export const GET_SINGLE_CERERI_SUCCESS='GET_SINGLE_CERERI_SUCCESS'

export const GET_SINGLE_CONTRACT_BEGIN='GET_SINGLE_CONTRACT_BEGIN'
export const GET_SINGLE_CONTRACT_SUCCESS='GET_SINGLE_CONTRACT_SUCCESS'

export const SET_EDIT_CERERI='SET_EDIT_CERERI'
export const SET_EDIT_CONTRACT='SET_EDIT_CONTRACT'