export const DISPLAY_ALERT='SHOW_ALERT';
export const CLEAR_ALERT='CLEAR_ALERT';

export const REGISTER_USER_BEGIN='REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS='REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR='REGISTER_USER_ERROR';

export const LOGIN_USER_BEGIN='LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR='LOGIN_USER_ERROR';

export const HANDLE_CHANGE='HANDLE_CHANGE';

export const CREATE_CERERE_BEGIN='CREATE_CERERE_BEGIN';
export const CREATE_CERERE_SUCCESS='CREATE_CERERE_SUCCESS';
export const CREATE_CERERE_ERROR='CREATE_CERERE_ERROR';

export const CREATE_CONTRACT_BEGIN='CREATE_CONTRACT_BEGIN';
export const CREATE_CONTRACT_SUCCESS='CREATE_CONTRACT_SUCCESS';
export const CREATE_CONTRACT_ERROR='CREATE_CONTRACT_ERROR';

export const LOGOUT_USER='LOGOUT_USER';

export const SIDEBAR_OPEN = 'SIDEBAR_OPEN'
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE'
